name: Test PRs

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Build the site
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install
        bundle exec jekyll build
#    - name: Test the HTML
#      run: bash scripts/test/html_proofer_staging.sh
