name: Test PRs

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
    - name: Build the site
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install
        bundle add rexml
        bundle exec jekyll build
    - name: Test the HTML
      run: bash scripts/test/html_proofer_staging.sh
